apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-tests-go-gxzmrmmh-import-imported
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-go-gxzmrmmh-import-imported 
  name: e2e-tests-go-gxzmrmmh-import-imported
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: e2e-tests-go-gxzmrmmh-import-imported
    weight: 100 
